### PR TITLE
Update Alike to v1.300

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @alexeiva!

I QA the font, and saw some issues that we need to solve before pushing an update.
I solved a lot of them, but there is still an issue with the Glyphset coverage: a lot of Glyphs are missing, to follow the GF Latin Core.

See the screenshots below: the pink ones are the new glyphs, but many of them are automatically generated. I need you to complete the yellow glyphs. Is this something you can do? You'll find the source in this PR, I kept the colours.

Don't hesitate if you have any questions,
Cheers!

Capture d’écran 2023-10-27 à 14 19 37
Capture d’écran 2023-10-27 à 14 19 44

### CODE REVIEW

**Comment by alexeiva** [comment]
Bonjour Emma, 

I am happy to complete the yellow glyphs today. 

tous meilleurs,

**Comment by emmamarichal** [comment]
Hello @alexeiva,
Thanks a lot! Could you merge this PR to avoid any conflict when you'll update the file?
Merci! :)

**Comment by alexeiva** [comment]
> Hello @alexeiva, Thanks a lot! Could you merge this PR to avoid any conflict when you'll update the file? Merci! :)

I have now updated the repo with added yellow glyphs

**Comment by emmamarichal** [comment]
Excellent, thanks a lot!

**Pull request merged**
